config/routes.rb
Rails.application.routes.draw do
  resources :options do
  resources :comments
  end
  get "/pages/:page" => "pages#show"
  root "pages#show", page: "home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/option.rb
class Option < ApplicationRecord
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  include OptionsHelper
  def index
    @options = Option.all
  end
  def show
    @options = Option.find(params[:id])
  end
  def new
    @options = Option.new
  end
  def create
    @options = Option.new(option_params)
    @options.count0 = 0
    @options.count1 = 0
    @options.id = maxoption + 1
    @options.save
    redirect_to options_path
  end
  def destroy
    @options = Option.find(params[:id])
    @options.destroy
    redirect_to options_path
  end
  def edit
  @options = Option.find(params[:id])
end
  def update
  @options = Option.find(params[:id])
  @options.update(option_params)
  redirect_to option_path
end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
     render template: "pages/#{params[:page]}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/options_helper.rb
module OptionsHelper
  def option_params
  params.require(:option).permit(:id, :option0, :option1, :count0, :count1)
end
def maxoption
  if Option.count == 0
    0
  else
    Option.last.id
  end
 end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DG01</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/options/edit.html.erb
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>ZERO or 1</title>
    <meta name="description" content="a simple A or B type market-research tool">
    <link rel="stylesheet" href="home.css">
</head>
<body>
<header>
    <div class=logo> <a href="/">
      <img src="https://farm5.staticflickr.com/4381/23557816978_0f72f5f26d_m.jpg" width="240" height="240" alt="0•1 LOGO"> </div>
</a></header>

<section>
      <div class=finished>

<h1>Edit an Option</h1>
<%= form_for(@options) do |f| %>
  <ul>
  <% @options.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>

  <p>
    <%= f.label "First Option"%><br />
    <%= f.text_field :option0 %>
  </p>
  <p>
    <%= f.label "Second Option" %><br />
    <%= f.text_field :option1 %>
  </p>
  <p>
    <%= f.submit %>
  </p>

</div>

</section>
</body>
<footer>
<div class=footertag>
    <p>A DataGap product</p>
</div>
</footer>
<% end %>

app/views/options/index.html.erb
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>ZERO or 1</title>
    <meta name="description" content="a simple A or B type market-research tool">
    <link rel="stylesheet" href="home.css">
</head>
<body>
<header>
  <div class=logo> <a href="/">
    <img src="https://farm5.staticflickr.com/4381/23557816978_0f72f5f26d_m.jpg" width="240" height="240" alt="0•1 LOGO"> </div>
</a></header>

<section>
      <div class=finished>
<h1>All Options</h1>

<ul id="options">
  <% @options.each do |option| %>
    <li>
      <%= link_to "Option "+option.id.to_s, option_path(option) %>
      <%= link_to "Delete", option_path(option), method: :delete,data: {confirm: "Really delete the option?"}%>
      <%= link_to "Edit", edit_option_path(option) %>
    </li>
  <% end %>
</ul>


<%= link_to "Create a New Option", new_option_path, class: "new_option" %>
</div>

</section>
</body>
<footer>
<div class=footertag>
    <p>A DataGap product</p>
</div>
</footer>

app/views/options/new.html.erb
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>ZERO or 1</title>
    <meta name="description" content="a simple A or B type market-research tool">
    <link rel="stylesheet" href="home.css">
</head>
<body>
<header>
  <div class=logo> <a href="/">
    <img src="https://farm5.staticflickr.com/4381/23557816978_0f72f5f26d_m.jpg" width="240" height="240" alt="0•1 LOGO"> </div>
</a></header>

<section>
      <div class=finished>

<h1>Create a New Option</h1>
<%= form_for(@options) do |f| %>
  <ul>
  <% @options.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>

  <p>
    <%= f.label "First Option"%><br />
    <%= f.text_field :option0 %>
  </p>
  <p>
    <%= f.label "Second Option" %><br />
    <%= f.text_field :option1 %>
  </p>
  <p>
    <%= f.submit %>
  </p>

</div>

</section>
</body>
<footer>
<div class=footertag>
    <p>A DataGap product</p>
</div>
</footer>
<% end %>

app/views/options/show.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>ZERO or 1</title>
    <meta name="description" content="a simple A or B type market-research tool">
    <link rel="stylesheet" href="choice.css">
</head>

<body>
 <header>    <div class=logo> <a href="/">
       <img src="https://farm5.staticflickr.com/4381/23557816978_0f72f5f26d_m.jpg" width="240" height="240" alt="0•1 LOGO"> </div>
 </a></header>

    <div class=panelholders>
    <% if @options.id < maxoption %>
    <% nextpage = "/options/"+(@options.id + 1).to_s %>
    <% else %>
    <% nextpage = "/pages/finish" %>
    <% end %>
    <div class=panelholderzero>
        <%= link_to @options.option0, nextpage %>
     </div>
    <div class=panelholderone>
        <%= link_to @options.option1, nextpage %>
    </div>
    </div>
</body>
<footer>
    <div class="footertag">
        <p>A DataGap product</p>
    </div>
</footer>

app/views/pages/finish.html.erb
<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>ZERO or 1</title>
        <meta name="description" content="a simple A or B type market-research tool">
        <link rel="stylesheet" href="finish.css">
    </head>
    <body>
        <header>
            <div class=logo> <a href="/">
              <img src="https://farm5.staticflickr.com/4381/23557816978_0f72f5f26d_m.jpg" width="240" height="240" alt="0•1 LOGO"> </div>
        </a></header>
        <section>
            <div class=finished>
                <h2>FINISHED!</h2>
                <p>Now you’ve answered every question we could ever ask you, there is nobody but your mother that understands your wants and needs better than us.<br><br>As soon as we’ve put your data to good use, we will e-mail you!<br><br>Promise.
                </p>
                </div>
        </section>
    </body>
    <footer>
    <div class=footertag>
        <p>A DataGap product</p>
    </div>
</footer>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>ZERO or 1</title>
    <meta name="description" content="a simple A or B type market-research tool">
    <link rel="stylesheet" href="home.css">
</head>
<body>
<header>
    <div class=logo> <img src="https://farm5.staticflickr.com/4381/23557816978_0f72f5f26d_m.jpg" width="240" height="240" alt="0•1 LOGO"> </div>
</header>
<section>
    <div class=container>
    <div class=welcome>
        <p><b>Welcome to 0 or 1</b> - the data-collection app that understands people’s preferences and needs.</p>
        </div>

        <div class=startbutton>
          <% if maxoption > 0 %>
          <a href="/options/1">START</a>
          <% else %>
          <a href="/pages/finish">START</a>
          <% end %>
        </div>
    </div>
</section>

    </body>
<footer>
    <div class=footertag>
        <p>A DataGap product</p>
    </div>
</footer>